Description: Deploy ECR registry

#----------------------------------------------------------
#---------------------PARAMETERS---------------------------
#----------------------------------------------------------
Parameters:
  Title:
    Type: String
    Description: Global title for all resources
    Default: relay42

#----------------------------------------------------------
#---------------------RESOURCES----------------------------
#----------------------------------------------------------
Resources:
  ECRRegistry:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref Title
      RepositoryPolicyText: {
        "Version": "2008-10-17",
        "Statement": [
          {
            "Sid": "AllowPushPull",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
              "ecr:GetDownloadUrlForLayer",
              "ecr:BatchGetImage",
              "ecr:BatchCheckLayerAvailability",
              "ecr:PutImage",
              "ecr:InitiateLayerUpload",
              "ecr:UploadLayerPart",
              "ecr:CompleteLayerUpload"
            ]
          }
        ]
      }
